# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Thu Apr 28 15:07:05 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(480, 800)
        MainWindow.setCursor(QtCore.Qt.BlankCursor)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exit = QtGui.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(400, 750, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.exit.setFont(font)
        self.exit.setObjectName("exit")
        self.bdice = QtGui.QPushButton(self.centralwidget)
        self.bdice.setGeometry(QtCore.QRect(10, 650, 101, 91))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.bdice.setFont(font)
        self.bdice.setObjectName("bdice")
        self.dice_spinbox = QtGui.QSpinBox(self.centralwidget)
        self.dice_spinbox.setGeometry(QtCore.QRect(230, 750, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.dice_spinbox.setFont(font)
        self.dice_spinbox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.dice_spinbox.setMinimum(1)
        self.dice_spinbox.setMaximum(6)
        self.dice_spinbox.setObjectName("dice_spinbox")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 461, 631))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.num_pad = QtGui.QWidget(self.tab)
        self.num_pad.setEnabled(True)
        self.num_pad.setGeometry(QtCore.QRect(0, 80, 451, 511))
        self.num_pad.setObjectName("num_pad")
        self.gridLayoutWidget = QtGui.QWidget(self.num_pad)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 331, 501))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.b2 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b2.sizePolicy().hasHeightForWidth())
        self.b2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.gridLayout.addWidget(self.b2, 1, 1, 1, 1)
        self.bf2 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bf2.sizePolicy().hasHeightForWidth())
        self.bf2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bf2.setFont(font)
        self.bf2.setObjectName("bf2")
        self.gridLayout.addWidget(self.bf2, 0, 2, 1, 1)
        self.b9 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b9.sizePolicy().hasHeightForWidth())
        self.b9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.b9.setFont(font)
        self.b9.setObjectName("b9")
        self.gridLayout.addWidget(self.b9, 3, 2, 1, 1)
        self.bread = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bread.sizePolicy().hasHeightForWidth())
        self.bread.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(50)
        font.setBold(False)
        self.bread.setFont(font)
        self.bread.setObjectName("bread")
        self.gridLayout.addWidget(self.bread, 0, 0, 1, 1)
        self.b0 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b0.sizePolicy().hasHeightForWidth())
        self.b0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.b0.setFont(font)
        self.b0.setObjectName("b0")
        self.gridLayout.addWidget(self.b0, 4, 1, 1, 1)
        self.b8 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b8.sizePolicy().hasHeightForWidth())
        self.b8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.b8.setFont(font)
        self.b8.setObjectName("b8")
        self.gridLayout.addWidget(self.b8, 3, 1, 1, 1)
        self.b5 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b5.sizePolicy().hasHeightForWidth())
        self.b5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.b5.setFont(font)
        self.b5.setObjectName("b5")
        self.gridLayout.addWidget(self.b5, 2, 1, 1, 1)
        self.b6 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b6.sizePolicy().hasHeightForWidth())
        self.b6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.b6.setFont(font)
        self.b6.setObjectName("b6")
        self.gridLayout.addWidget(self.b6, 2, 2, 1, 1)
        self.bcls = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bcls.sizePolicy().hasHeightForWidth())
        self.bcls.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.bcls.setFont(font)
        self.bcls.setObjectName("bcls")
        self.gridLayout.addWidget(self.bcls, 4, 2, 1, 1)
        self.b1 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b1.sizePolicy().hasHeightForWidth())
        self.b1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.b1.setFont(font)
        self.b1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b1.setAutoRepeat(False)
        self.b1.setAutoRepeatInterval(100)
        self.b1.setObjectName("b1")
        self.gridLayout.addWidget(self.b1, 1, 0, 1, 1)
        self.b4 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b4.sizePolicy().hasHeightForWidth())
        self.b4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.b4.setFont(font)
        self.b4.setObjectName("b4")
        self.gridLayout.addWidget(self.b4, 2, 0, 1, 1)
        self.binit = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.binit.sizePolicy().hasHeightForWidth())
        self.binit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(50)
        font.setBold(False)
        self.binit.setFont(font)
        self.binit.setObjectName("binit")
        self.gridLayout.addWidget(self.binit, 0, 1, 1, 1)
        self.b00 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b00.sizePolicy().hasHeightForWidth())
        self.b00.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.b00.setFont(font)
        self.b00.setObjectName("b00")
        self.gridLayout.addWidget(self.b00, 4, 0, 1, 1)
        self.b3 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b3.sizePolicy().hasHeightForWidth())
        self.b3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.b3.setFont(font)
        self.b3.setObjectName("b3")
        self.gridLayout.addWidget(self.b3, 1, 2, 1, 1)
        self.b7 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b7.sizePolicy().hasHeightForWidth())
        self.b7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.b7.setFont(font)
        self.b7.setObjectName("b7")
        self.gridLayout.addWidget(self.b7, 3, 0, 1, 1)
        self.verticalLayoutWidget = QtGui.QWidget(self.num_pad)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(340, 10, 103, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btrans = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btrans.sizePolicy().hasHeightForWidth())
        self.btrans.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btrans.setFont(font)
        self.btrans.setObjectName("btrans")
        self.verticalLayout.addWidget(self.btrans)
        self.bmns = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bmns.sizePolicy().hasHeightForWidth())
        self.bmns.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.bmns.setFont(font)
        self.bmns.setObjectName("bmns")
        self.verticalLayout.addWidget(self.bmns)
        self.bpls = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bpls.sizePolicy().hasHeightForWidth())
        self.bpls.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.bpls.setFont(font)
        self.bpls.setObjectName("bpls")
        self.verticalLayout.addWidget(self.bpls)
        self.bequ = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bequ.sizePolicy().hasHeightForWidth())
        self.bequ.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.bequ.setFont(font)
        self.bequ.setObjectName("bequ")
        self.verticalLayout.addWidget(self.bequ)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 2)
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(0, 10, 441, 71))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.display = QtGui.QLineEdit(self.frame)
        self.display.setEnabled(False)
        self.display.setGeometry(QtCore.QRect(10, 10, 421, 51))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.display.setFont(font)
        self.display.setCursor(QtCore.Qt.BlankCursor)
        self.display.setMouseTracking(False)
        self.display.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.display.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.display.setAutoFillBackground(False)
        self.display.setInputMask("")
        self.display.setMaxLength(17)
        self.display.setFrame(False)
        self.display.setEchoMode(QtGui.QLineEdit.Normal)
        self.display.setCursorPosition(1)
        self.display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.display.setDragEnabled(False)
        self.display.setReadOnly(True)
        self.display.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.display.setObjectName("display")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 451, 541))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_attr1 = QtGui.QHBoxLayout()
        self.horizontalLayout_attr1.setObjectName("horizontalLayout_attr1")
        self.attr1_label = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.attr1_label.setFont(font)
        self.attr1_label.setObjectName("attr1_label")
        self.horizontalLayout_attr1.addWidget(self.attr1_label)
        self.attr1_bm5 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr1_bm5.sizePolicy().hasHeightForWidth())
        self.attr1_bm5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr1_bm5.setFont(font)
        self.attr1_bm5.setObjectName("attr1_bm5")
        self.horizontalLayout_attr1.addWidget(self.attr1_bm5)
        self.attr1_bm1 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr1_bm1.sizePolicy().hasHeightForWidth())
        self.attr1_bm1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr1_bm1.setFont(font)
        self.attr1_bm1.setObjectName("attr1_bm1")
        self.horizontalLayout_attr1.addWidget(self.attr1_bm1)
        self.attr1_lcd = QtGui.QLCDNumber(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.attr1_lcd.setFont(font)
        self.attr1_lcd.setMidLineWidth(7)
        self.attr1_lcd.setSmallDecimalPoint(False)
        self.attr1_lcd.setNumDigits(3)
        self.attr1_lcd.setDigitCount(3)
        self.attr1_lcd.setMode(QtGui.QLCDNumber.Dec)
        self.attr1_lcd.setProperty("value", 0.0)
        self.attr1_lcd.setObjectName("attr1_lcd")
        self.horizontalLayout_attr1.addWidget(self.attr1_lcd)
        self.attr1_bp1 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr1_bp1.sizePolicy().hasHeightForWidth())
        self.attr1_bp1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr1_bp1.setFont(font)
        self.attr1_bp1.setObjectName("attr1_bp1")
        self.horizontalLayout_attr1.addWidget(self.attr1_bp1)
        self.attr1_bp5 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr1_bp5.sizePolicy().hasHeightForWidth())
        self.attr1_bp5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr1_bp5.setFont(font)
        self.attr1_bp5.setObjectName("attr1_bp5")
        self.horizontalLayout_attr1.addWidget(self.attr1_bp5)
        self.horizontalLayout_attr1.setStretch(0, 2)
        self.horizontalLayout_attr1.setStretch(1, 1)
        self.horizontalLayout_attr1.setStretch(2, 1)
        self.horizontalLayout_attr1.setStretch(3, 5)
        self.horizontalLayout_attr1.setStretch(4, 1)
        self.horizontalLayout_attr1.setStretch(5, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_attr1)
        self.horizontalLayout_attr2 = QtGui.QHBoxLayout()
        self.horizontalLayout_attr2.setObjectName("horizontalLayout_attr2")
        self.attr2_label = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.attr2_label.setFont(font)
        self.attr2_label.setObjectName("attr2_label")
        self.horizontalLayout_attr2.addWidget(self.attr2_label)
        self.attr2_bm5 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr2_bm5.sizePolicy().hasHeightForWidth())
        self.attr2_bm5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr2_bm5.setFont(font)
        self.attr2_bm5.setObjectName("attr2_bm5")
        self.horizontalLayout_attr2.addWidget(self.attr2_bm5)
        self.attr2_bm1 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr2_bm1.sizePolicy().hasHeightForWidth())
        self.attr2_bm1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr2_bm1.setFont(font)
        self.attr2_bm1.setObjectName("attr2_bm1")
        self.horizontalLayout_attr2.addWidget(self.attr2_bm1)
        self.attr2_lcd = QtGui.QLCDNumber(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.attr2_lcd.setFont(font)
        self.attr2_lcd.setMidLineWidth(7)
        self.attr2_lcd.setSmallDecimalPoint(False)
        self.attr2_lcd.setNumDigits(3)
        self.attr2_lcd.setDigitCount(3)
        self.attr2_lcd.setMode(QtGui.QLCDNumber.Dec)
        self.attr2_lcd.setProperty("value", 0.0)
        self.attr2_lcd.setObjectName("attr2_lcd")
        self.horizontalLayout_attr2.addWidget(self.attr2_lcd)
        self.attr2_bp1 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr2_bp1.sizePolicy().hasHeightForWidth())
        self.attr2_bp1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr2_bp1.setFont(font)
        self.attr2_bp1.setObjectName("attr2_bp1")
        self.horizontalLayout_attr2.addWidget(self.attr2_bp1)
        self.attr2_bp5 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr2_bp5.sizePolicy().hasHeightForWidth())
        self.attr2_bp5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr2_bp5.setFont(font)
        self.attr2_bp5.setObjectName("attr2_bp5")
        self.horizontalLayout_attr2.addWidget(self.attr2_bp5)
        self.horizontalLayout_attr2.setStretch(0, 2)
        self.horizontalLayout_attr2.setStretch(1, 1)
        self.horizontalLayout_attr2.setStretch(2, 1)
        self.horizontalLayout_attr2.setStretch(3, 5)
        self.horizontalLayout_attr2.setStretch(4, 1)
        self.horizontalLayout_attr2.setStretch(5, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_attr2)
        self.horizontalLayout_attr3 = QtGui.QHBoxLayout()
        self.horizontalLayout_attr3.setObjectName("horizontalLayout_attr3")
        self.attr3_label = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.attr3_label.setFont(font)
        self.attr3_label.setObjectName("attr3_label")
        self.horizontalLayout_attr3.addWidget(self.attr3_label)
        self.attr3_bm5 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr3_bm5.sizePolicy().hasHeightForWidth())
        self.attr3_bm5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr3_bm5.setFont(font)
        self.attr3_bm5.setObjectName("attr3_bm5")
        self.horizontalLayout_attr3.addWidget(self.attr3_bm5)
        self.attr3_bm1 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr3_bm1.sizePolicy().hasHeightForWidth())
        self.attr3_bm1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr3_bm1.setFont(font)
        self.attr3_bm1.setObjectName("attr3_bm1")
        self.horizontalLayout_attr3.addWidget(self.attr3_bm1)
        self.attr3_lcd = QtGui.QLCDNumber(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.attr3_lcd.setFont(font)
        self.attr3_lcd.setMidLineWidth(7)
        self.attr3_lcd.setSmallDecimalPoint(False)
        self.attr3_lcd.setNumDigits(3)
        self.attr3_lcd.setDigitCount(3)
        self.attr3_lcd.setMode(QtGui.QLCDNumber.Dec)
        self.attr3_lcd.setProperty("value", 0.0)
        self.attr3_lcd.setObjectName("attr3_lcd")
        self.horizontalLayout_attr3.addWidget(self.attr3_lcd)
        self.attr3_bp1 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr3_bp1.sizePolicy().hasHeightForWidth())
        self.attr3_bp1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr3_bp1.setFont(font)
        self.attr3_bp1.setObjectName("attr3_bp1")
        self.horizontalLayout_attr3.addWidget(self.attr3_bp1)
        self.attr3_bp5 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr3_bp5.sizePolicy().hasHeightForWidth())
        self.attr3_bp5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr3_bp5.setFont(font)
        self.attr3_bp5.setObjectName("attr3_bp5")
        self.horizontalLayout_attr3.addWidget(self.attr3_bp5)
        self.horizontalLayout_attr3.setStretch(0, 2)
        self.horizontalLayout_attr3.setStretch(1, 1)
        self.horizontalLayout_attr3.setStretch(2, 1)
        self.horizontalLayout_attr3.setStretch(3, 5)
        self.horizontalLayout_attr3.setStretch(4, 1)
        self.horizontalLayout_attr3.setStretch(5, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_attr3)
        self.horizontalLayout_attr4 = QtGui.QHBoxLayout()
        self.horizontalLayout_attr4.setObjectName("horizontalLayout_attr4")
        self.attr4_label = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.attr4_label.setFont(font)
        self.attr4_label.setObjectName("attr4_label")
        self.horizontalLayout_attr4.addWidget(self.attr4_label)
        self.attr4_bm5 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr4_bm5.sizePolicy().hasHeightForWidth())
        self.attr4_bm5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr4_bm5.setFont(font)
        self.attr4_bm5.setObjectName("attr4_bm5")
        self.horizontalLayout_attr4.addWidget(self.attr4_bm5)
        self.attr4_bm1 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr4_bm1.sizePolicy().hasHeightForWidth())
        self.attr4_bm1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr4_bm1.setFont(font)
        self.attr4_bm1.setObjectName("attr4_bm1")
        self.horizontalLayout_attr4.addWidget(self.attr4_bm1)
        self.attr4_lcd = QtGui.QLCDNumber(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.attr4_lcd.setFont(font)
        self.attr4_lcd.setMidLineWidth(7)
        self.attr4_lcd.setSmallDecimalPoint(False)
        self.attr4_lcd.setNumDigits(3)
        self.attr4_lcd.setDigitCount(3)
        self.attr4_lcd.setMode(QtGui.QLCDNumber.Dec)
        self.attr4_lcd.setProperty("value", 0.0)
        self.attr4_lcd.setObjectName("attr4_lcd")
        self.horizontalLayout_attr4.addWidget(self.attr4_lcd)
        self.attr4_bp1 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr4_bp1.sizePolicy().hasHeightForWidth())
        self.attr4_bp1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr4_bp1.setFont(font)
        self.attr4_bp1.setObjectName("attr4_bp1")
        self.horizontalLayout_attr4.addWidget(self.attr4_bp1)
        self.attr4_bp5 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr4_bp5.sizePolicy().hasHeightForWidth())
        self.attr4_bp5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr4_bp5.setFont(font)
        self.attr4_bp5.setObjectName("attr4_bp5")
        self.horizontalLayout_attr4.addWidget(self.attr4_bp5)
        self.horizontalLayout_attr4.setStretch(0, 2)
        self.horizontalLayout_attr4.setStretch(1, 1)
        self.horizontalLayout_attr4.setStretch(2, 1)
        self.horizontalLayout_attr4.setStretch(3, 5)
        self.horizontalLayout_attr4.setStretch(4, 1)
        self.horizontalLayout_attr4.setStretch(5, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_attr4)
        self.horizontalLayout_attr5 = QtGui.QHBoxLayout()
        self.horizontalLayout_attr5.setObjectName("horizontalLayout_attr5")
        self.attr5_label = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.attr5_label.setFont(font)
        self.attr5_label.setObjectName("attr5_label")
        self.horizontalLayout_attr5.addWidget(self.attr5_label)
        self.attr5_bm5 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr5_bm5.sizePolicy().hasHeightForWidth())
        self.attr5_bm5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr5_bm5.setFont(font)
        self.attr5_bm5.setObjectName("attr5_bm5")
        self.horizontalLayout_attr5.addWidget(self.attr5_bm5)
        self.attr5_bm1 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr5_bm1.sizePolicy().hasHeightForWidth())
        self.attr5_bm1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr5_bm1.setFont(font)
        self.attr5_bm1.setObjectName("attr5_bm1")
        self.horizontalLayout_attr5.addWidget(self.attr5_bm1)
        self.attr5_lcd = QtGui.QLCDNumber(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.attr5_lcd.setFont(font)
        self.attr5_lcd.setMidLineWidth(7)
        self.attr5_lcd.setSmallDecimalPoint(False)
        self.attr5_lcd.setNumDigits(3)
        self.attr5_lcd.setDigitCount(3)
        self.attr5_lcd.setMode(QtGui.QLCDNumber.Dec)
        self.attr5_lcd.setProperty("value", 0.0)
        self.attr5_lcd.setObjectName("attr5_lcd")
        self.horizontalLayout_attr5.addWidget(self.attr5_lcd)
        self.attr5_bp1 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr5_bp1.sizePolicy().hasHeightForWidth())
        self.attr5_bp1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr5_bp1.setFont(font)
        self.attr5_bp1.setObjectName("attr5_bp1")
        self.horizontalLayout_attr5.addWidget(self.attr5_bp1)
        self.attr5_bp5 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr5_bp5.sizePolicy().hasHeightForWidth())
        self.attr5_bp5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr5_bp5.setFont(font)
        self.attr5_bp5.setObjectName("attr5_bp5")
        self.horizontalLayout_attr5.addWidget(self.attr5_bp5)
        self.horizontalLayout_attr5.setStretch(0, 2)
        self.horizontalLayout_attr5.setStretch(1, 1)
        self.horizontalLayout_attr5.setStretch(2, 1)
        self.horizontalLayout_attr5.setStretch(3, 5)
        self.horizontalLayout_attr5.setStretch(4, 1)
        self.horizontalLayout_attr5.setStretch(5, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_attr5)
        self.horizontalLayout_attr6 = QtGui.QHBoxLayout()
        self.horizontalLayout_attr6.setObjectName("horizontalLayout_attr6")
        self.attr6_label = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.attr6_label.setFont(font)
        self.attr6_label.setObjectName("attr6_label")
        self.horizontalLayout_attr6.addWidget(self.attr6_label)
        self.attr6_bm5 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr6_bm5.sizePolicy().hasHeightForWidth())
        self.attr6_bm5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr6_bm5.setFont(font)
        self.attr6_bm5.setObjectName("attr6_bm5")
        self.horizontalLayout_attr6.addWidget(self.attr6_bm5)
        self.attr6_bm1 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr6_bm1.sizePolicy().hasHeightForWidth())
        self.attr6_bm1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr6_bm1.setFont(font)
        self.attr6_bm1.setObjectName("attr6_bm1")
        self.horizontalLayout_attr6.addWidget(self.attr6_bm1)
        self.attr6_lcd = QtGui.QLCDNumber(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.attr6_lcd.setFont(font)
        self.attr6_lcd.setMidLineWidth(7)
        self.attr6_lcd.setSmallDecimalPoint(False)
        self.attr6_lcd.setNumDigits(3)
        self.attr6_lcd.setDigitCount(3)
        self.attr6_lcd.setMode(QtGui.QLCDNumber.Dec)
        self.attr6_lcd.setProperty("value", 0.0)
        self.attr6_lcd.setObjectName("attr6_lcd")
        self.horizontalLayout_attr6.addWidget(self.attr6_lcd)
        self.attr6_bp1 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr6_bp1.sizePolicy().hasHeightForWidth())
        self.attr6_bp1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr6_bp1.setFont(font)
        self.attr6_bp1.setObjectName("attr6_bp1")
        self.horizontalLayout_attr6.addWidget(self.attr6_bp1)
        self.attr6_bp5 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr6_bp5.sizePolicy().hasHeightForWidth())
        self.attr6_bp5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attr6_bp5.setFont(font)
        self.attr6_bp5.setObjectName("attr6_bp5")
        self.horizontalLayout_attr6.addWidget(self.attr6_bp5)
        self.horizontalLayout_attr6.setStretch(0, 2)
        self.horizontalLayout_attr6.setStretch(1, 1)
        self.horizontalLayout_attr6.setStretch(2, 1)
        self.horizontalLayout_attr6.setStretch(3, 5)
        self.horizontalLayout_attr6.setStretch(4, 1)
        self.horizontalLayout_attr6.setStretch(5, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_attr6)
        self.attr_bread = QtGui.QPushButton(self.tab_2)
        self.attr_bread.setGeometry(QtCore.QRect(260, 550, 91, 51))
        self.attr_bread.setObjectName("attr_bread")
        self.attr_bwrite = QtGui.QPushButton(self.tab_2)
        self.attr_bwrite.setGeometry(QtCore.QRect(350, 550, 101, 51))
        self.attr_bwrite.setObjectName("attr_bwrite")
        self.attr_bzero = QtGui.QPushButton(self.tab_2)
        self.attr_bzero.setGeometry(QtCore.QRect(170, 550, 91, 51))
        self.attr_bzero.setObjectName("attr_bzero")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 650, 341, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dice1_label = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.dice1_label.setFont(font)
        self.dice1_label.setObjectName("dice1_label")
        self.horizontalLayout.addWidget(self.dice1_label)
        self.dice2_label = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.dice2_label.setFont(font)
        self.dice2_label.setObjectName("dice2_label")
        self.horizontalLayout.addWidget(self.dice2_label)
        self.dice3_label = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.dice3_label.setFont(font)
        self.dice3_label.setObjectName("dice3_label")
        self.horizontalLayout.addWidget(self.dice3_label)
        self.dice4_label = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.dice4_label.setFont(font)
        self.dice4_label.setObjectName("dice4_label")
        self.horizontalLayout.addWidget(self.dice4_label)
        self.dice5_label = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.dice5_label.setFont(font)
        self.dice5_label.setObjectName("dice5_label")
        self.horizontalLayout.addWidget(self.dice5_label)
        self.dice6_label = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.dice6_label.setFont(font)
        self.dice6_label.setObjectName("dice6_label")
        self.horizontalLayout.addWidget(self.dice6_label)
        self.brelease = QtGui.QPushButton(self.centralwidget)
        self.brelease.setGeometry(QtCore.QRect(320, 750, 81, 41))
        self.brelease.setObjectName("brelease")
        self.dice_sum = QtGui.QLabel(self.centralwidget)
        self.dice_sum.setGeometry(QtCore.QRect(120, 750, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.dice_sum.setFont(font)
        self.dice_sum.setObjectName("dice_sum")
        self.dice_sum_label = QtGui.QLabel(self.centralwidget)
        self.dice_sum_label.setGeometry(QtCore.QRect(29, 750, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.dice_sum_label.setFont(font)
        self.dice_sum_label.setObjectName("dice_sum_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.exit, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.exit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.bdice.setText(QtGui.QApplication.translate("MainWindow", "Dice", None, QtGui.QApplication.UnicodeUTF8))
        self.b2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.bf2.setText(QtGui.QApplication.translate("MainWindow", "F2", None, QtGui.QApplication.UnicodeUTF8))
        self.b9.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.bread.setText(QtGui.QApplication.translate("MainWindow", "Read", None, QtGui.QApplication.UnicodeUTF8))
        self.b0.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.b8.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.b5.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.b6.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.bcls.setText(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.b1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.b4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.binit.setText(QtGui.QApplication.translate("MainWindow", "Init", None, QtGui.QApplication.UnicodeUTF8))
        self.b00.setText(QtGui.QApplication.translate("MainWindow", "00", None, QtGui.QApplication.UnicodeUTF8))
        self.b3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.b7.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.btrans.setText(QtGui.QApplication.translate("MainWindow", "Trans", None, QtGui.QApplication.UnicodeUTF8))
        self.bmns.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.bpls.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.bequ.setText(QtGui.QApplication.translate("MainWindow", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.display.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.attr1_label.setText(QtGui.QApplication.translate("MainWindow", "Attr1", None, QtGui.QApplication.UnicodeUTF8))
        self.attr1_bm5.setText(QtGui.QApplication.translate("MainWindow", "-5", None, QtGui.QApplication.UnicodeUTF8))
        self.attr1_bm1.setText(QtGui.QApplication.translate("MainWindow", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.attr1_bp1.setText(QtGui.QApplication.translate("MainWindow", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.attr1_bp5.setText(QtGui.QApplication.translate("MainWindow", "+5", None, QtGui.QApplication.UnicodeUTF8))
        self.attr2_label.setText(QtGui.QApplication.translate("MainWindow", "Attr2", None, QtGui.QApplication.UnicodeUTF8))
        self.attr2_bm5.setText(QtGui.QApplication.translate("MainWindow", "-5", None, QtGui.QApplication.UnicodeUTF8))
        self.attr2_bm1.setText(QtGui.QApplication.translate("MainWindow", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.attr2_bp1.setText(QtGui.QApplication.translate("MainWindow", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.attr2_bp5.setText(QtGui.QApplication.translate("MainWindow", "+5", None, QtGui.QApplication.UnicodeUTF8))
        self.attr3_label.setText(QtGui.QApplication.translate("MainWindow", "Attr3", None, QtGui.QApplication.UnicodeUTF8))
        self.attr3_bm5.setText(QtGui.QApplication.translate("MainWindow", "-5", None, QtGui.QApplication.UnicodeUTF8))
        self.attr3_bm1.setText(QtGui.QApplication.translate("MainWindow", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.attr3_bp1.setText(QtGui.QApplication.translate("MainWindow", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.attr3_bp5.setText(QtGui.QApplication.translate("MainWindow", "+5", None, QtGui.QApplication.UnicodeUTF8))
        self.attr4_label.setText(QtGui.QApplication.translate("MainWindow", "Attr4", None, QtGui.QApplication.UnicodeUTF8))
        self.attr4_bm5.setText(QtGui.QApplication.translate("MainWindow", "-5", None, QtGui.QApplication.UnicodeUTF8))
        self.attr4_bm1.setText(QtGui.QApplication.translate("MainWindow", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.attr4_bp1.setText(QtGui.QApplication.translate("MainWindow", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.attr4_bp5.setText(QtGui.QApplication.translate("MainWindow", "+5", None, QtGui.QApplication.UnicodeUTF8))
        self.attr5_label.setText(QtGui.QApplication.translate("MainWindow", "Attr5", None, QtGui.QApplication.UnicodeUTF8))
        self.attr5_bm5.setText(QtGui.QApplication.translate("MainWindow", "-5", None, QtGui.QApplication.UnicodeUTF8))
        self.attr5_bm1.setText(QtGui.QApplication.translate("MainWindow", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.attr5_bp1.setText(QtGui.QApplication.translate("MainWindow", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.attr5_bp5.setText(QtGui.QApplication.translate("MainWindow", "+5", None, QtGui.QApplication.UnicodeUTF8))
        self.attr6_label.setText(QtGui.QApplication.translate("MainWindow", "Attr6", None, QtGui.QApplication.UnicodeUTF8))
        self.attr6_bm5.setText(QtGui.QApplication.translate("MainWindow", "-5", None, QtGui.QApplication.UnicodeUTF8))
        self.attr6_bm1.setText(QtGui.QApplication.translate("MainWindow", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.attr6_bp1.setText(QtGui.QApplication.translate("MainWindow", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.attr6_bp5.setText(QtGui.QApplication.translate("MainWindow", "+5", None, QtGui.QApplication.UnicodeUTF8))
        self.attr_bread.setText(QtGui.QApplication.translate("MainWindow", "Read", None, QtGui.QApplication.UnicodeUTF8))
        self.attr_bwrite.setText(QtGui.QApplication.translate("MainWindow", "Write", None, QtGui.QApplication.UnicodeUTF8))
        self.attr_bzero.setText(QtGui.QApplication.translate("MainWindow", "Zero", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.dice1_label.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.dice2_label.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.dice3_label.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.dice4_label.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.dice5_label.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.dice6_label.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.brelease.setText(QtGui.QApplication.translate("MainWindow", "release", None, QtGui.QApplication.UnicodeUTF8))
        self.dice_sum.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.dice_sum_label.setText(QtGui.QApplication.translate("MainWindow", "SUM:", None, QtGui.QApplication.UnicodeUTF8))

